name: Test license

on:
  workflow_dispatch:

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  activation:
    name: Test license
    runs-on: ubuntu-latest
    steps:
      # Test license was correctly pasted to secrets
      - name: Test license via activation
        uses: game-ci/unity-activate@v1.3
        with:
          unityVersion: 2020.1.8f1
